server:
  port: 8001

dubbo:
  application:
    ##### 注册服务的名称
    name: consumer
  ##### 注册中心地址
  registry:
    address: zookeeper://localhost:2181
    group: test
  ##### 调用服务超时时间
  consumer:
    timeout: 5000

spring:
  output:
    ansi:
      enabled: always #复制代码
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp